--DROP TABLE ARMAZENA CASCADE CONSTRAINTS; 
--DROP TABLE VENDA CASCADE CONSTRAINTS; 
--DROP TABLE ESTOQUE CASCADE CONSTRAINTS; 
--DROP TABLE CARNE CASCADE CONSTRAINTS;
--DROP TABLE ESTOQUE_ATUAL CASCADE CONSTRAINT;
--DROP TABLE VENDIDO CASCADE CONSTRAINT;   
--DROP TABLE CONFIGURACOES CASCADE CONSTRAINT;  

CREATE TABLE CARNE (
    ID_CARNE NUMBER(5) CONSTRAINT CARNE_ID_CARNE_PK PRIMARY KEY,
    NOME VARCHAR2(50) NOT NULL,
    TIPO VARCHAR2(20)NOT NULL,
    PRECO NUMBER(10,2) NOT NULL
);

CREATE TABLE ESTOQUE (
    ID_ESTOQUE NUMBER(11) CONSTRAINT ESTOQUE_ID_ESTOQUE_PK PRIMARY KEY,
    QUANTIDADE_ADICIONADA NUMBER(10, 2)NOT NULL,
    DATA_ADICAO DATE NOT NULL,
    DATA_VALIDADE DATE NOT NULL
);

CREATE TABLE ESTOQUE_ATUAL ( 
    ID_ESTOQUE_ATUAL NUMBER(9) CONSTRAINT ESTOQUE_ATUAL_PK PRIMARY KEY, 
    ID_CARNE NUMBER(5) CONSTRAINT ESTOQUE_ATUAL_CARNE_FK REFERENCES CARNE(ID_CARNE)
);

CREATE TABLE VENDA ( 
    ID_VENDA NUMBER(10) PRIMARY KEY,
    PESO DECIMAL(10, 3), 
    PRECO_TOTAL DECIMAL(10, 2), 
    DATA_VENDA DATE DEFAULT SYSDATE,
    ID_ESTOQUE NUMBER(11)
);

CREATE TABLE ARMAZENA (
    ID_CARNE NUMBER(5) NOT NULL,
    ID_ESTOQUE NUMBER(10) NOT NULL,
    CONSTRAINT ARMAZENA_CARNE_FK FOREIGN KEY(ID_CARNE) REFERENCES CARNE(ID_CARNE),
    CONSTRAINT ARMAZENA_ESTOQUE_FK FOREIGN KEY(ID_ESTOQUE) REFERENCES ESTOQUE(ID_ESTOQUE),
    CONSTRAINT ARMAZENA_PK PRIMARY KEY (ID_CARNE, ID_ESTOQUE)
);

CREATE TABLE VENDIDO (
    ID_VENDA NUMBER(10),
    ID_CARNE NUMBER(5),
    CONSTRAINT VENDIDO_PK PRIMARY KEY (ID_VENDA, ID_CARNE),
    CONSTRAINT VENDIDO_VENDA_FK FOREIGN KEY (ID_VENDA) REFERENCES VENDA (ID_VENDA),
    CONSTRAINT VENDIDO_CARNE_FK FOREIGN KEY (ID_CARNE) REFERENCES CARNE (ID_CARNE)
);

CREATE TABLE CONFIGURACOES (
    ID_CONFIGURACAO NUMBER(4) PRIMARY KEY,
    NOME_CONFIGURACAO VARCHAR2(50),
    VALOR_CONFIGURACAO NUMBER(5)
);


INSERT INTO CONFIGURACOES (ID_CONFIGURACAO, NOME_CONFIGURACAO, VALOR_CONFIGURACAO)
VALUES (1, 'LIMITE_ESTOQUE', 77);
COMMIT;

